workflows:
  ios-workflow:
    name: iOS Workflow - Development Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      groups:
        - aqua_horizon_env  # Reference to environment variable group
      vars:
        BUNDLE_ID: "com.aqua_horizon.app.testProject"
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Flutter analyze
        script: |
          flutter analyze
      - name: Flutter unit tests
        script: |
          flutter test
        ignore_failure: true
      - name: Build iOS app
        script: |
          flutter build ios --release \
            --dart-define=SUPABASE_URL="$SUPABASE_URL" \
            --dart-define=SUPABASE_ANON_KEY="$SUPABASE_ANON_KEY" \
            --no-codesign
    artifacts:
      - build/ios/Runner.app
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - user@example.com
        notify:
          success: true
          failure: false
